### ISSUE TITLE
guidata-test3 for python3 version ?

### ISSUE THREAD

**Issue by picca** [PierreRaybaut/guidata#3]
Hello, 

I am preparing the Debina package and I would like to know what is the best way to deal with the python2 and python3 version of the guidata-tests (scripts)

to my opinion it would be nice to rename it as guidata-tests3 like ipython did with ipython3.

What is your opinion ?

**Comment by picca** [comment]
Inded It would be nice to have the same for guiqwt-tests :)

**Comment by PierreRaybaut** [comment]
I propose to rename them this way:
guidata-tests-py2 and guidata-tests-py3, respectively for Python 2 and Python 3

**Comment by PierreRaybaut** [comment]
Ok, I guess that you would have to patch setup.py when building the debian package?

Because I don't know how to (and if it's even possible to) build a single source package containing both scripts (guidata-tests-py2 and guidata-tests-py3) and install the script that match target Python version. As far as I know, the only way to do that would be to build specific source packages (one for Python 2, one for Python 3).

**Comment by picca** [comment]
In spyder I think that the trick is implented
in the setup.py you have

# Check for Python 3
PY3 = sys.version_info[0] == 3
# NOTE: the '[...]_win_post_install.py' script is installed even on non-Windows
# platforms due to a bug in pip installation process (see Issue 1158)
SCRIPTS = ['%s_win_post_install.py' % NAME]
if PY3 and sys.platform.startswith('linux'):
    SCRIPTS.append('spyder3')
else:
    SCRIPTS.append('spyder')

Is it what you need ?

**Comment by PierreRaybaut** [comment]
Nevermind... I was tired and somehow forgot about the distinction between ``MANIFEST.in`` and ``setup.py``: by including _**all**_ the scripts (linux, Windows, Python 2, Python 3) in ``MANIFEST.in``, files will be included in source package even if setup.py does not include them (because ``setup.py`` will include only the files corresponding to the Python version used to build the package).
