### ISSUE TITLE
No module named 'guidata.qt' error

### ISSUE THREAD

**Issue by aspence** [PierreRaybaut/guidata#49]
Thank you for this great package.

In a fresh conda environment, after installing guidata via conda-forge, I get the error in the title `No module named 'guidata.qt' error` when running

`from guidata.qt.QtGui import QMainWindow, QSplitter`

Any help appreciated, can send more info as needed!

**Comment by aspence** [comment]
FYI installing guidata=1.7.6 works fine on the system, so it's something between 1.7.6 and 1.7.9. cheers

**Comment by PierreRaybaut** [comment]
Actually, since last summer (https://github.com/PierreRaybaut/guidata/commit/3da4a9d7ebfffa2d3eec75ed683c0e4d7f9768b5), guidata relies on QtPy (Qt bindings compatibility layer which was greatly inspired from the same original code as guidata, i.e. Spyder).

So, since v1.7.9 (https://github.com/PierreRaybaut/guidata/blob/master/CHANGELOG.md#version-179), guidata uses QtPy.

This:
`from guidata.qt.QtGui import QMainWindow`
should be replaced by that:
`from qtpy.QtWidgets import QMainWindow`
